import React from 'react';
import './SASQueriesModal.css';

// Mock SAS queries that correspond to the file being UAT'd
const generateSASQueries = (file) => `/* SAS Query for: ${file.fileName} */
/* Department: ${file.department || 'N/A'} */
/* Owner: ${file.owner || 'N/A'} */
/* Generated by SparkSAS Compare Tool */

LIBNAME pyspark_in "&data_path/pyspark_output";
LIBNAME sas_out    "&data_path/sas_output";

/* Step 1: Load PySpark output reference */
PROC IMPORT
    DATAFILE="&data_path/pyspark/${file.fileName}"
    OUT=work.pyspark_ref
    DBMS=CSV REPLACE;
    GETNAMES=YES;
RUN;

/* Step 2: Run equivalent SAS transformation */
DATA work.sas_transformed;
    SET pyspark_in.source_data;
    /* Apply same business logic as PySpark script */
    /* Replace this block with your SAS equivalent logic */
    FORMAT _numeric_ best12.;
    FORMAT _character_ $200.;
RUN;

/* Step 3: Export SAS output for comparison */
PROC EXPORT
    DATA=work.sas_transformed
    OUTFILE="&output_path/sas_output_${file.fileName}"
    DBMS=CSV REPLACE;
RUN;

/* Step 4: Optional - Quick sanity check */
PROC MEANS DATA=work.sas_transformed N NMISS MIN MAX MEAN;
RUN;`;

export const SASQueriesModal = ({ file, onClose }) => (
  <div className="modal-overlay" onClick={onClose}>
    <div className="sas-modal" onClick={e => e.stopPropagation()}>
      <button className="modal-close" onClick={onClose}>✕</button>
      <h2 className="modal-title">SAS Queries</h2>
      <p className="modal-subtitle">
        Run these queries in your SAS environment to generate the SAS output file, then upload the result.
      </p>

      <div className="sas-info-banner">
        <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="#2563eb" strokeWidth="2">
          <circle cx="12" cy="12" r="10"/><line x1="12" y1="8" x2="12" y2="12"/><line x1="12" y1="16" x2="12.01" y2="16"/>
        </svg>
        Run these queries behind the scenes in SAS, then upload the output file using the Upload SAS Output button.
      </div>

      <div className="sas-code-wrap">
        <button
          className="copy-btn"
          onClick={() => navigator.clipboard?.writeText(generateSASQueries(file))}
          title="Copy to clipboard"
        >
          Copy
        </button>
        <pre className="sas-code">{generateSASQueries(file)}</pre>
      </div>

      <div className="modal-footer" style={{ marginTop: 24 }}>
        <button className="btn-secondary" onClick={onClose}>Close</button>
      </div>
    </div>
  </div>
);
